<?php

/**
 * This function generates the results set of the tblProducts in the specified category
 *
 * @param $meat String the category to limit the search with, defaults to all
 * @return array $products - an assoc. array which contains all the names stored in the DB.
 */
function getProducts($meat)
{
    $meat = filter_var($meat, FILTER_SANITIZE_SPECIAL_CHARS);
	
	global $dbc;
	
	//determine what category we want to search for, default to everything
    if ($meat == 'freshCuts'){
        $where = "WHERE cat_id = 1;";
    }
    elseif($meat == 'sausages'){
        $where = "WHERE cat_id = 2;";
    }
    else{
        $where = '';
    }
    
    $query = 'SELECT prod_id, prod_name, prod_weight, prod_price, prod_description, prod_image, cat_name 
    FROM ICS199db.tblProducts 
    JOIN ICS199db.tblCategory 
    ON tblCategory_cat_id = cat_id ' . $where;

    $statement = $dbc->prepare($query);
    $statement->execute();
    $products = $statement->fetchAll();
    $statement->closeCursor();
    return $products;

}

/**
 * This function generates the results set of the tblProducts for the specified item
 *
 * @param $item String the item to limit the search with, defaults to all
 * @return array $products - an assoc. array which contains all the names that match from the DB.
 */
function getItem($item)
{
    $item = filter_var($item, FILTER_SANITIZE_SPECIAL_CHARS);
	
    //remove whitespace characters before search
    $item = trim($item);
    
	global $dbc;
	$item = "%" . $item . "%";
	
    $query = "SELECT prod_id, prod_name, prod_weight, prod_price, prod_description, prod_image, cat_name
                FROM ICS199db.tblProducts
                JOIN ICS199db.tblCategory
                ON tblCategory_cat_id = cat_id 
				WHERE upper(prod_name) LIKE upper(:item) OR upper(cat_name) LIKE upper(:item);";
    $statement = $dbc->prepare($query);
	$statement->bindValue(':item', $item);
    $statement->execute();
    $products = $statement->fetchAll();
    $statement->closeCursor();
    return $products;
}

/**
 * Helper function that looks up the customerID of a sessionID
 *
 * @param $sessionID String the sessionID to search for
 * @return int $custID - the customerID
 */
function getCustomerID($sessionID){
	
	//$sessionID = filter_input(INPUT_GET, $sessionID, FILTER_SANITIZE_SPECIAL_CHARS);
	
	global $dbc;
	
	//checks db to see if customer exists. If not, adds to customer table and creates a new order number.  Regardless, return the orderID
	$query = 'SELECT session_id FROM ICS199db.tblCustomers WHERE session_id = :sessionID;';
	$statement = $dbc->prepare($query);
	$statement->bindValue(':sessionID', $sessionID);
    $statement->execute();
    $results = $statement->fetch();
    $statement->closeCursor();
	//var_dump($results);
	//var_dump(empty($results));
	
	//TODO: this doesnt work properly, we overwrite the sessionID everytime... isset works as expected when
	//you start with clear database but doesnt respond to there already being an entry
	if(empty($results)){
		//add new customer
		$query = 'INSERT INTO ICS199db.tblCustomers (session_id) VALUES (:sessionID);';
		$statement = $dbc->prepare($query);
		$statement->bindValue(':sessionID', $sessionID, PDO::PARAM_STR);
		$statement->execute();
		$statement->closeCursor();
	}
	
	//we need cust_id to find our order
	$query = 'SELECT cust_id FROM ICS199db.tblCustomers WHERE session_id = :sessionID;';
	$statement = $dbc->prepare($query);
	$statement->bindValue(':sessionID', $sessionID);
    $statement->execute();
    $results = $statement->fetchAll();
    $statement->closeCursor();
	
	$custID = $results[0]['cust_id'];
	return $custID;
}

/* Dont use an orderID anymore, custID + prodID gives unique rows
function getOrderID($custID){
	global $dbc;
	
	//do we have an existing order?
	$query = 'SELECT order_id FROM ICS199db.tblOrder WHERE cust_id = ' . $custID . ';';
	$statement = $dbc->prepare($query);
    $statement->execute();
    $results = $statement->fetchAll();
    $statement->closeCursor();
	
	if(isset($results['order_id']) == false){
		//new order - autogenerated in sql so dont set
	} else {
		echo('order_id is set');
		$orderID = $results['order_id'];
	}
	
	return $orderID;
}
*/

/**
 * A function that adds a customer's cart to the database
 *
 * @param $sessionID String the sessionID of the order
 * @param $arrayOfProducts Array an array of productID:id qty:value keyvalue pairs
 * @return int $custID - the customerID
 */
function addProductToDB($sessionID, $arrayOfProducts){
	
	//$sessionID = filter_input(INPUT_GET, $sessionID, FILTER_SANITIZE_SPECIAL_CHARS);
	//$arrayOfProducts = filter_input(INPUT_GET, $arrayOfProducts, FILTER_SANITIZE_STRING);
	
	//prepare to talk to the database
	global $dbc;
	
	$custID = getCustomerID($sessionID);
	//is there already one of these in there?
	
	foreach($arrayOfProducts as $product){
		//SANITIZE EACH PRODUCT
		$product['productID'] = filter_var($product['productID'], FILTER_SANITIZE_SPECIAL_CHARS);
		$product['qty'] = filter_var($product['qty'], FILTER_SANITIZE_NUMBER_INT);
        
        //make sure its a positive value
        if($product['qty'] <= 0){
            //someone is bypassing form validation
            return;
        }
		
		$query = 'SELECT tblProducts_prod_id
					FROM ICS199db.tblOrder
					WHERE tblCustomers_cust_id = :custID
					AND tblProducts_prod_id = :productID;';
		$statement = $dbc->prepare($query);
		$statement->bindValue(':custID', $custID);
		$statement->bindValue(':productID', $product['productID']);
		$statement->execute();
		$results = $statement->fetchAll();
		$statement->closeCursor();

		if(empty($results)){
			//none exists, add new product
			$query = 'INSERT INTO ICS199db.tblOrder (tblProducts_prod_id, tblCustomers_cust_id, prod_qty)
						VALUES (:productID, :custID, :qty)';
			$statement = $dbc->prepare($query);
			$statement->bindValue(':productID', $product['productID']);
			$statement->bindValue(':custID', $custID);
			$statement->bindValue(':qty', $product['qty']);
			$statement->execute();
			$statement->closeCursor();
		} else {
			//already there, just increase qty
			$query = 'UPDATE ICS199db.tblOrder 
						SET prod_qty = prod_qty + :qty
						WHERE tblProducts_prod_id = :productID
						AND tblCustomers_cust_id = :custID;';
			$statement = $dbc->prepare($query);
			$statement->bindValue(':productID', $product['productID']);
			$statement->bindValue(':custID', $custID);
			$statement->bindValue(':qty', $product['qty']);
			$statement->execute();
			$statement->closeCursor();
		}
	}
}

/**
 * Function is used to retrieve what products user currently has in shoppingcart
 *
 * @param $sessinID String the sessionID of the order
 */
function getUserCart($sessionID){
	
	//$sessionID = filter_input(INPUT_GET, $sessionID, FILTER_SANITIZE_SPECIAL_CHARS);
	
	 global $dbc;
	
	//determine what category we want to search for, default to everything
    $custid = getCustomerID($sessionID);
    $query = 'SELECT p.prod_id, p.prod_name, p.prod_weight, p.prod_price, p.prod_image, o.prod_qty
		FROM ICS199db.tblOrder o
		JOIN ICS199db.tblProducts p
		ON p.prod_id = o.tblProducts_prod_id
		WHERE tblCustomers_cust_id = :cust_id;';

    $statement = $dbc->prepare($query);
	$statement->bindValue(':cust_id', $custid);
    $statement->execute();
    $products = $statement->fetchAll();
    $statement->closeCursor();
    return $products;

}

/**
 * Function is used to remove products from shoppingcart with current sessionID
 *
 * @param $sessinID String the sessionID of the order
 * @param $arrayOfProducts Array an array of productID:id qty:value keyvalue pairs
 */
function removeProductFromDB($sessionID, $arrayOfProducts){
	
	//$sessionID = filter_input(INPUT_GET, $sessionID, FILTER_SANITIZE_SPECIAL_CHARS);
	
	//prepare to talk to the database
	global $dbc;
	$custID = getCustomerID($sessionID);
	
	foreach($arrayOfProducts as $product){
		//SANITIZE EACH PRODUCT
		$product['productID'] = filter_var($product['productID'], FILTER_SANITIZE_SPECIAL_CHARS);
		$product['qty'] = filter_var($product['qty'], FILTER_SANITIZE_NUMBER_INT);
		
        //make sure its a positive value
        if($product['qty'] <= 0){
            //someone is bypassing form validation
            return;
        }
        
		$query = 'SELECT prod_qty
					FROM ICS199db.tblOrder
					WHERE tblCustomers_cust_id = :custID
					AND tblProducts_prod_id = :productID;';
		$statement = $dbc->prepare($query);
		$statement->bindValue(':custID', $custID);
		$statement->bindValue(':productID', $product['productID']);
		$statement->execute();
		$results = $statement->fetch();
		$statement->closeCursor();
	
		//how many are there in the cart?  Grab the qty
		$dbProductQty = $results['prod_qty'];

		//remove requested qty or all if it is >= to db qty
		if($product['qty'] >= $dbProductQty){
			//remove everything
			$query = 'DELETE FROM ICS199db.tblOrder
				WHERE tblCustomers_cust_id = :custID
				AND tblProducts_prod_id = :productID;';
			$statement = $dbc->prepare($query);
			$statement->bindValue(':productID', $product['productID']);
			$statement->bindValue(':custID', $custID);
			$statement->execute();
			$statement->closeCursor();
		} else {
			//remove specified qty - this is a UPDATE
			$query = 'UPDATE ICS199db.tblOrder 
						SET prod_qty = prod_qty - :qty
						WHERE tblProducts_prod_id = :productID
						AND tblCustomers_cust_id = :custID;';
			$statement = $dbc->prepare($query);
			$statement->bindValue(':productID', $product['productID']);
			$statement->bindValue(':custID', $custID);
			$statement->bindValue(':qty', $product['qty']);
			$statement->execute();
			$statement->closeCursor();
		}
	}
}

/**
 * Function is used to remove all products from shoppingcart with current sessionID
 *
 * @param $sessinID String the sessionID of the order
 */
function clearCart($sessionID){
	
	//$sessionID = filter_input(INPUT_GET, $sessionID, FILTER_SANITIZE_SPECIAL_CHARS);
	
	global $dbc;
	$query = 'DELETE FROM ICS199db.tblOrder
				WHERE tblCustomers_cust_id = :custID;';
	$statement = $dbc->prepare($query);
	$custID = getCustomerID($sessionID);
	$statement->bindValue(':custID', $custID);
	$statement->execute();
	$statement->closeCursor();
}

/**
 * Function is used to assign a orderID for the current sessionID
 *
 * @param $sessinID String the sessionID of the order
 */
function storeOrder($sessionID) {
	
	//$sessionID = filter_input(INPUT_GET, $sessionID, FILTER_SANITIZE_SPECIAL_CHARS);
	
	global $dbc;
	//Query highest value of order_id to increment and assign to newest order!
	$query = 'SELECT MAX(order_id) FROM ICS199db.tblConfirmedOrder;';
	$statement = $dbc->prepare($query);
	$statement->execute();
	$result = $statement->fetch();
	
	if (!isset($result)) {
		$newOrderID = 1;
	} else {
		$newOrderID = $result["MAX(order_id)"] + 1;
	}

	//Get current cart and clone into tblConfirmedOrder table with new order_id
	$custID = getCustomerID($sessionID);
	
	$query = 'SELECT * FROM ICS199db.tblOrder
				WHERE tblCustomers_cust_id = :custID;';
	$statement = $dbc->prepare($query);
	$statement->bindValue(':custID', $custID);
	$statement->execute();
	$finalCart = $statement->fetchAll();
	$statement->closeCursor();
	
	$query = 'INSERT INTO ICS199db.tblConfirmedOrder (tblProducts_prod_id, tblCustomers_cust_id, prod_qty, order_date, order_id)
			VALUES (:productID, :custID, :qty, :date, :order_id);';
	$statement = $dbc->prepare($query);
	
	foreach ($finalCart as $product) {
		$statement->bindValue(':productID', $product['tblProducts_prod_id']);	
		$statement->bindValue(':custID', $product['tblCustomers_cust_id']);
		$statement->bindValue(':qty', $product['prod_qty']);
		$statement->bindValue(':date', $product['order_date']);
		$statement->bindValue(':order_id', $newOrderID);
		$statement->execute();
		$statement->closeCursor();
	}
    
    //remove cart from customers current cart so they can make a new one if they want
    clearCart($sessionID);
	return $newOrderID;
}


?>
